version: 2.1

references:
  - &on_branches_and_tags
    filters:
      tags:
        only: 
          - /.*/
  - &on_tags_only
    filters:
      branches:
        ignore:
        - /.*/
      tags:
        only:
        - /.*/


jobs:
  test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      # - run:
      #     name: Compile code
      #     command: swift build --verbose
      # - run:
      #     name: Run unit tests
      #     command: swift test
      - run:
          name: Login in quay.io
          command: docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}" quay.io
      - run:
          name: Build image
          command: make build

  deploy:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Login in quay.io
          command: docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}" quay.io
      - run:
          name: Deploy image
          command: make install

workflows:
  version: 2

  test-n-deploy:
    jobs:
      - test:
          context: babylon
          <<: *on_branches_and_tags
      - deploy:
          context: babylon
          requires: [test]
          <<: *on_tags_only
