version: 2

jobs:
  test:
    docker:
      - image: swift:4.2
    steps:
      - checkout
      - run: 
          name: Compile code
          command: swift build
      - run: 
          name: Run unit tests
          command: swift test

workflows:
  version: 2
  tests:
    jobs:
      - test
