version: 2.1

commands:
  quay_login:
    steps:
      - run: docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}" quay.io


jobs:
  test:
    docker:
      - image: swift:4.2
    steps:
      - checkout
      - run:
          name: Compile code
          command: swift build
      - run:
          name: Run unit tests
          command: swift test
    
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Build image
          command: make build

  deploy:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - quay_login 
      - run: echo "Success"
      # - run:
      #     name: Deploy image
      #     command: make install

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test:
          context: babylon
      - build:
          context: babylon
          requires: 
            - test
      - deploy:
          context: babylon
          requires: 
            - build
          filters:
            # branches:
            #   ignore:
            #     - /.*/
            tags:
              only: /^v.*/
